In [1]:
import numpy as np

In [2]:
minha_lista = [1, 2, 3]

In [3]:
minha_lista

[1, 2, 3]

In [4]:
np.array(minha_lista)

array([1, 2, 3])

In [6]:
minha_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
np.random.rand(5)

array([0.25233854, 0.49348518, 0.69282081, 0.72171545, 0.8860672 ])

In [19]:
np.random.rand(5) * 100

array([22.29547505, 14.82351773, 23.14139463, 58.39417804, 37.70809121])

In [20]:
np.random.randn(5)

array([ 1.62071331,  1.7332845 ,  0.83613439, -1.53609549,  1.58131186])

In [21]:
np.random.randint(5)

4

In [22]:
np.random.randint(0, 100)

13

In [24]:
np.random.randint(0, 101, 100)

array([50, 69, 21, 70, 29, 54, 42, 61, 99, 93, 36, 97, 39, 33, 18, 15, 87,
       28, 66, 55, 99, 53, 75, 74,  6, 74, 29, 24, 97, 65, 89, 77, 41, 80,
       27, 61, 57, 67, 45, 55, 91, 22, 50, 18, 31, 76,  8, 78, 12, 87, 38,
       95, 39, 94, 72, 40, 90, 47, 72,  6, 11,  4, 27, 54, 79, 73, 11, 96,
       80, 97, 63, 20, 68, 46, 10,  5, 30, 18, 23, 22, 83, 63, 43, 88,  5,
        4, 81, 30, 13, 60,  7, 48,  4,  0, 71, 15,  6, 84, 91, 96])

In [25]:
arr = np.random.rand(25)

In [26]:
arr

array([0.55522245, 0.41532359, 0.23534324, 0.19870534, 0.1073907 ,
       0.441215  , 0.80444343, 0.89177036, 0.72661511, 0.33785565,
       0.24779273, 0.52191609, 0.01260033, 0.25125371, 0.54405279,
       0.81344885, 0.704416  , 0.10572392, 0.37744519, 0.53361042,
       0.58095618, 0.0558306 , 0.22075016, 0.5033679 , 0.34864348])

In [27]:
arr.reshape((5,5))

array([[0.55522245, 0.41532359, 0.23534324, 0.19870534, 0.1073907 ],
       [0.441215  , 0.80444343, 0.89177036, 0.72661511, 0.33785565],
       [0.24779273, 0.52191609, 0.01260033, 0.25125371, 0.54405279],
       [0.81344885, 0.704416  , 0.10572392, 0.37744519, 0.53361042],
       [0.58095618, 0.0558306 , 0.22075016, 0.5033679 , 0.34864348]])

In [28]:
arr.max()

0.8917703634049865

In [29]:
arr.min()

0.01260032959945978

In [30]:
arr.argmax()

7

In [31]:
arr.argmin()

12