In [39]:
import numpy as np

In [40]:
arr = np.arange(0, 30, 3)

In [41]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [42]:
arr[3]

9

In [43]:
arr[2:5]

array([ 6,  9, 12])

In [44]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [45]:
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [46]:
arr[7:] = 100

In [47]:
arr

array([  0,   3,   6,   9,  12,  15,  18, 100, 100, 100])

In [48]:
arr = np.arange(1, 51).reshape((5,10))

In [49]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [50]:
arr[:3][:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [51]:
arr2 = arr[:3]

In [52]:
arr2[:] = 50

In [53]:
arr

array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [54]:
arr3 = arr2[:2].copy()

In [55]:
arr3[:] = 100

In [56]:
arr3

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [57]:
arr2

array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])

In [62]:
arr

array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [59]:
arr[0:4,5:]

array([[50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [36, 37, 38, 39, 40]])

In [71]:
bol = arr < 50

In [72]:
arr[bol]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])